// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahrdwyfpdonqxnnaaruq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFocmR3eWZwZG9ucXhubmFhcnVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDEzMDQsImV4cCI6MjA3Mjk3NzMwNH0.0-Fk6_blJDB0Jnq8-V6gUIJDw5ZAlMEr8F6V1onmEsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});